'use strict';
const crypto=require('node:crypto');
const ADDRESS=/^0x[a-fA-F0-9]{40}$/;
const TRANSITIONS={draft:['simulated'],simulated:['reviewed'],reviewed:['voting'],voting:['succeeded','defeated','cancelled'],succeeded:['execution_ready'],execution_ready:['executed','execution_failed'],defeated:[],cancelled:[],executed:[],execution_failed:['execution_ready']};
function normalizeProposal(input){if(!input||typeof input!=='object')throw new Error('proposal is required');if(typeof input.title!=='string'||!input.title.trim())throw new Error('title is required');if(typeof input.description!=='string'||input.description.trim().length<20)throw new Error('description must contain at least 20 characters');const actions=(input.actions||[]).map((a)=>{if(!ADDRESS.test(a.target))throw new Error('action target must be a checksummed-compatible EVM address');if(!/^0x[a-fA-F0-9]*$/.test(a.calldata||''))throw new Error('calldata must be hexadecimal');if(String(a.valueWei||'').startsWith('-')||!/^[0-9]+$/.test(String(a.valueWei||'')))throw new Error('valueWei must be unsigned integer text');return{target:a.target.toLowerCase(),calldata:a.calldata.toLowerCase(),valueWei:String(a.valueWei)};});if(!actions.length)throw new Error('at least one executable action is required');return{title:input.title.trim(),description:input.description.trim(),actions};}
function proposalHash(proposal,chainId,governorAddress,snapshotBlock){if(!Number.isSafeInteger(Number(chainId))||Number(chainId)<=0)throw new Error('valid chainId required');if(!ADDRESS.test(governorAddress))throw new Error('valid governor address required');if(!Number.isSafeInteger(Number(snapshotBlock))||Number(snapshotBlock)<0)throw new Error('valid snapshotBlock required');return crypto.createHash('sha256').update(JSON.stringify({proposal:normalizeProposal(proposal),chainId:String(chainId),governorAddress:governorAddress.toLowerCase(),snapshotBlock:String(snapshotBlock)})).digest('hex');}
function tally(votes,quorumUnits){let forUnits=0n,againstUnits=0n,abstainUnits=0n;const seen=new Set();for(const vote of votes){if(seen.has(vote.voter.toLowerCase()))throw new Error('duplicate voter');seen.add(vote.voter.toLowerCase());const power=BigInt(vote.votingPowerUnits);if(power<0n)throw new Error('negative voting power');if(vote.choice==='for')forUnits+=power;else if(vote.choice==='against')againstUnits+=power;else if(vote.choice==='abstain')abstainUnits+=power;else throw new Error('invalid vote choice');}const participation=forUnits+againstUnits+abstainUnits;return{forUnits:forUnits.toString(),againstUnits:againstUnits.toString(),abstainUnits:abstainUnits.toString(),participationUnits:participation.toString(),quorumReached:participation>=BigInt(quorumUnits),passed:participation>=BigInt(quorumUnits)&&forUnits>againstUnits};}
function assertTransition(from,to,role,context={}){if(!(TRANSITIONS[from]||[]).includes(to))throw new Error(`invalid transition: ${from} -> ${to}`);if(to==='simulated'&&(!context.simulationBlockHash||!context.stateDiffHash||context.success!==true))throw new Error('simulation requires successful block-pinned state diff');if(to==='voting'&&(!context.snapshotBlockHash||!context.quorumUnits||!context.deadline))throw new Error('voting requires block-pinned snapshot, quorum, and deadline');if(['succeeded','defeated'].includes(to)&&(!context.tallyHash||!context.finalizedBlockHash||context.confirmations<Number(context.requiredConfirmations||1)))throw new Error('finalization requires tally hash and confirmed canonical block');if(to==='execution_ready'&&(role!=='executor'||!context.freshSimulationHash))throw new Error('execution readiness requires executor and fresh simulation');if(to==='executed'&&(!context.walletSignature||!context.transactionHash))throw new Error('execution requires an explicit wallet signature and transaction hash');return true;}
module.exports={normalizeProposal,proposalHash,tally,assertTransition};
